spring.application.name=vehicle-api

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/vehicle_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
